const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const port = Number(process.env.PORT || 4000);
const allowedOrigins = (process.env.FRONTEND_ORIGIN || 'http://localhost:5173,https://findam-website-3lj6fggfh-kumterencefuh-coders-projects.vercel.app').split(',').map(value => value.trim()).filter(Boolean);
const isProduction = process.env.NODE_ENV === 'production';
const adminToken = process.env.ADMIN_TOKEN || (isProduction ? '' : 'findam-admin-dev-token');
const authSecret = process.env.AUTH_SECRET || (isProduction ? '' : 'findam-development-secret-change-me');
const dataFile = path.resolve(__dirname, '..', process.env.DATA_FILE || 'data/db.json');
const uploadDir = path.resolve(__dirname, '..', 'uploads');

const seed = [
  { id: 'listing-buea-001', title: 'Bright 2 Bedroom Apartment', city: 'Buea', neighbourhood: 'Molyko', type: 'Rent', price: 150000, period: 'month', beds: 2, baths: 2, size: 82, featured: true, verified: true, hue: 24, description: 'A clean, bright apartment close to schools, shops and transport routes.' },
  { id: 'listing-bamenda-001', title: 'Family Home with Compound', city: 'Bamenda', neighbourhood: 'Commercial Avenue', type: 'Rent', price: 220000, period: 'month', beds: 3, baths: 2, size: 145, featured: true, verified: true, hue: 178, description: 'A spacious family home with a secure compound and practical access to town.' },
  { id: 'listing-yaounde-001', title: 'Modern Studio near Bastos', city: 'Yaounde', neighbourhood: 'Bastos', type: 'Rent', price: 180000, period: 'month', beds: 1, baths: 1, size: 48, featured: true, verified: true, hue: 310, description: 'A modern studio in a well-connected neighbourhood, ideal for a professional.' }
];

function ensureStore() {
  fs.mkdirSync(path.dirname(dataFile), { recursive: true });
  if (!fs.existsSync(dataFile)) fs.writeFileSync(dataFile, JSON.stringify({ listings: seed, submissions: [], favorites: [], inquiries: [] }, null, 2));
}
if (isProduction && (!adminToken || adminToken.length < 24 || !authSecret || authSecret.length < 24)) throw new Error('Production requires ADMIN_TOKEN and AUTH_SECRET of at least 24 characters');
function readStore() { ensureStore(); const store = JSON.parse(fs.readFileSync(dataFile, 'utf8')); store.users ||= []; const rootEmail = String(process.env.ROOT_ADMIN_EMAIL || '').trim().toLowerCase(); const rootPassword = process.env.ROOT_ADMIN_PASSWORD; if (rootEmail && rootPassword && !store.users.some(user => user.email === rootEmail)) { store.users.push({ id: id(), email: rootEmail, name: process.env.ROOT_ADMIN_NAME || 'Findam Root Admin', passwordHash: hashPassword(rootPassword), role: 'root_admin', createdAt: new Date().toISOString() }); fs.writeFileSync(dataFile, JSON.stringify(store, null, 2)); } const adminEmail = String(process.env.ADMIN_EMAIL || '').trim().toLowerCase(); const adminPassword = process.env.ADMIN_PASSWORD; if (adminEmail && adminPassword && !store.users.some(user => user.email === adminEmail)) { store.users.push({ id: id(), email: adminEmail, name: process.env.ADMIN_NAME || 'Findam Admin', passwordHash: hashPassword(adminPassword), role: 'admin', createdAt: new Date().toISOString() }); fs.writeFileSync(dataFile, JSON.stringify(store, null, 2)); } return store; }
function writeStore(store) { fs.writeFileSync(dataFile, JSON.stringify(store, null, 2)); }
function send(res, status, body) { const requestOrigin = res.req.headers.origin; const corsOrigin = requestOrigin || allowedOrigins[0]; res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'Referrer-Policy': 'no-referrer', 'Access-Control-Allow-Origin': corsOrigin, 'Vary': 'Origin', 'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,OPTIONS', 'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-Admin-Token' }); res.end(JSON.stringify(body)); }
function body(req) { return new Promise((resolve, reject) => { let raw = ''; req.on('data', chunk => { raw += chunk; if (raw.length > 15e6) reject(new Error('Payload too large')); }); req.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(new Error('Invalid JSON')); } }); }); }
function saveImages(photos = []) { fs.mkdirSync(uploadDir, { recursive: true }); return photos.slice(0, 6).filter(photo => typeof photo === 'string' && photo.startsWith('data:image/')).map((photo) => { const match = photo.match(/^data:image\/(jpeg|jpg|png|webp);base64,(.+)$/); if (!match) return null; const extension = match[1] === 'jpeg' ? 'jpg' : match[1]; const filename = `${crypto.randomUUID()}.${extension}`; fs.writeFileSync(path.join(uploadDir, filename), Buffer.from(match[2], 'base64')); return `/uploads/${filename}`; }).filter(Boolean); }
function id() { return crypto.randomUUID(); }
const requestCounts = new Map();
function isRateLimited(req) { const key = req.socket.remoteAddress || 'unknown'; const now = Date.now(); const entry = requestCounts.get(key) || { start: now, count: 0 }; if (now - entry.start > 60000) { entry.start = now; entry.count = 0; } entry.count += 1; requestCounts.set(key, entry); return entry.count > 120; }
function isAdmin(req) { const sessionUser = authUser(req); return Boolean((sessionUser && ['admin', 'root_admin'].includes(sessionUser.role)) || (adminToken && (req.headers['x-admin-token'] === adminToken || req.headers.authorization === `Bearer ${adminToken}`))); }
function isRootAdmin(req) { const user = authUser(req); return Boolean(user && user.role === 'root_admin'); }
// Keep legacy listings visible: older records used only `verified: true`, while
// newer records use the explicit confirmed status.
function publicListing(item) { return item.status === 'confirmed' || (item.verified === true && item.status !== 'rejected'); }
function hashPassword(password, salt = crypto.randomBytes(16).toString('hex')) { return `${salt}:${crypto.scryptSync(String(password), salt, 32).toString('hex')}`; }
function verifyPassword(password, stored) { const [salt, digest] = String(stored).split(':'); if (!salt || !digest) return false; const candidate = crypto.scryptSync(String(password), salt, 32).toString('hex'); return crypto.timingSafeEqual(Buffer.from(candidate), Buffer.from(digest)); }
function tokenFor(user) { const payload = Buffer.from(JSON.stringify({ sub: user.id, role: user.role, exp: Date.now() + 86400000 })).toString('base64url'); const signature = crypto.createHmac('sha256', authSecret).update(payload).digest('base64url'); return `${payload}.${signature}`; }
function validToken(token) { try { const [payload, signature] = String(token || '').split('.'); const expected = crypto.createHmac('sha256', authSecret).update(payload).digest('base64url'); if (!payload || !signature || !crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return false; return JSON.parse(Buffer.from(payload, 'base64url').toString()).exp > Date.now(); } catch { return false; } }
function authUser(req) { const raw = (req.headers.authorization || '').replace(/^Bearer\s+/i, ''); const payload = validToken(raw); if (!payload) return null; const store = readStore(); return (store.users || []).find(user => user.id === payload.sub) || null; }
function safeUser(user) { return user && { id: user.id, email: user.email, name: user.name, role: user.role, createdAt: user.createdAt }; }
function botReply(message = '') { const value = message.toLowerCase(); if (/verify|safe|inspect/.test(value)) return 'Every public listing is visited by a Findam house finder and reviewed by a civil engineer before publication.'; if (/price|cost|rent/.test(value)) return 'Prices are shown in FCFA. Use the listing filters to narrow results by city, type and maximum price.'; if (/list|landlord|photo/.test(value)) return 'Submit your title, city, type, price, phone number and property photos. We will arrange a visit and inspection.'; if (/city|location/.test(value)) return 'Findam currently covers Bamenda, Buea and Yaounde.'; return 'I can help with homes, prices, verification, cities and listing a property.'; }

async function handler(req, res) {
  if (isRateLimited(req)) return send(res, 429, { error: 'Too many requests' });
  if (req.method === 'OPTIONS') return send(res, 204, {});
  const url = new URL(req.url, `http://${req.headers.host}`); const parts = url.pathname.split('/').filter(Boolean); const store = readStore();
  if (req.method === 'GET' && parts[0] === 'uploads' && parts[1]) { const filename = path.basename(parts[1]); const file = path.join(uploadDir, filename); if (!fs.existsSync(file)) return send(res, 404, { error: 'Image not found' }); const extension = path.extname(file).toLowerCase(); const contentType = extension === '.png' ? 'image/png' : extension === '.webp' ? 'image/webp' : 'image/jpeg'; const requestOrigin = req.headers.origin; const corsOrigin = requestOrigin && allowedOrigins.includes(requestOrigin) ? requestOrigin : allowedOrigins[0]; res.writeHead(200, { 'Content-Type': contentType, 'Access-Control-Allow-Origin': corsOrigin, 'Vary': 'Origin', 'Cache-Control': 'public, max-age=31536000, immutable' }); return res.end(fs.readFileSync(file)); }
  if (req.method === 'GET' && url.pathname === '/') return send(res, 200, { service: 'Findam API', status: 'running', docs: ['/api/health', '/api/listings', '/api/favorites', '/api/bot'] });
  if (req.method === 'GET' && url.pathname === '/api/health') return send(res, 200, { status: 'ok', service: 'findam-api', time: new Date().toISOString() });
  if (req.method === 'POST' && url.pathname === '/api/auth/register') { const input = await body(req); if (!input.email || !input.password || String(input.password).length < 8) return send(res, 400, { error: 'Email and a password of at least 8 characters are required' }); store.users ||= []; if (store.users.some(user => user.email === input.email.toLowerCase())) return send(res, 409, { error: 'Account already exists' }); const user = { id: id(), email: input.email.toLowerCase(), name: input.name || '', passwordHash: hashPassword(input.password), role: 'user', createdAt: new Date().toISOString() }; store.users.push(user); writeStore(store); return send(res, 201, { data: { id: user.id, email: user.email, name: user.name, role: user.role }, token: tokenFor(user) }); }
  if (req.method === 'POST' && url.pathname === '/api/auth/login') { const input = await body(req); store.users ||= []; const user = store.users.find(item => item.email === String(input.email || '').toLowerCase() && verifyPassword(input.password, item.passwordHash)); if (!user) return send(res, 401, { error: 'Invalid email or password' }); return send(res, 200, { data: { id: user.id, email: user.email, name: user.name, role: user.role }, token: tokenFor(user) }); }
  if (req.method === 'GET' && url.pathname === '/api/auth/me') { const user = authUser(req); return user ? send(res, 200, { data: safeUser(user) }) : send(res, 401, { error: 'Authentication required' }); }
  if (req.method === 'POST' && url.pathname === '/api/inquiries') { const user = authUser(req); if (!user) return send(res, 401, { error: 'Please log in to contact the property owner' }); const input = await body(req); const listing = store.listings.find(item => String(item.id) === String(input.listingId)); if (!listing || !publicListing(listing)) return send(res, 404, { error: 'Rental listing not found' }); if (!['Rent', 'Guesthouse'].includes(listing.type)) return send(res, 400, { error: 'Inquiries are available for rental properties only' }); if (listing.ownerId === user.id) return send(res, 400, { error: 'You cannot inquire about your own property' }); const message = String(input.message || '').trim(); if (!message) return send(res, 400, { error: 'Message is required' }); store.inquiries ||= []; const inquiry = { id: id(), listingId: listing.id, tenantId: user.id, ownerId: listing.ownerId, messages: [{ senderId: user.id, text: message, createdAt: new Date().toISOString() }], status: 'new', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; store.inquiries.push(inquiry); writeStore(store); return send(res, 201, { data: inquiry, message: 'Inquiry sent to the property owner' }); }
  if (req.method === 'GET' && url.pathname === '/api/inquiries') { const user = authUser(req); if (!user) return send(res, 401, { error: 'Authentication required' }); store.inquiries ||= []; const data = store.inquiries.filter(item => item.tenantId === user.id || item.ownerId === user.id).map(item => ({ ...item, listing: store.listings.find(listing => listing.id === item.listingId) })).filter(item => item.listing); return send(res, 200, { data }); }
  if (req.method === 'POST' && parts[1] === 'inquiries' && parts[2] && parts[3] === 'reply') { const user = authUser(req); if (!user) return send(res, 401, { error: 'Authentication required' }); store.inquiries ||= []; const inquiry = store.inquiries.find(item => item.id === parts[2]); if (!inquiry || inquiry.ownerId !== user.id) return send(res, 404, { error: 'Inquiry not found' }); const message = String((await body(req)).message || '').trim(); if (!message) return send(res, 400, { error: 'Reply is required' }); inquiry.messages.push({ senderId: user.id, text: message, createdAt: new Date().toISOString() }); inquiry.status = 'replied'; inquiry.updatedAt = new Date().toISOString(); writeStore(store); return send(res, 200, { data: inquiry, message: 'Reply sent to the tenant' }); }
  if (req.method === 'GET' && url.pathname === '/api/admin/users') { if (!isRootAdmin(req)) return send(res, 403, { error: 'Root admin access required' }); return send(res, 200, { data: store.users.map(safeUser) }); }
  if (req.method === 'POST' && parts[1] === 'admin' && parts[2] === 'users' && parts[3] && parts[4] === 'promote') { if (!isRootAdmin(req)) return send(res, 403, { error: 'Root admin access required' }); const target = store.users.find(user => user.id === parts[3]); if (!target) return send(res, 404, { error: 'User not found' }); if (target.role === 'root_admin') return send(res, 400, { error: 'Root admin cannot be changed' }); target.role = 'admin'; writeStore(store); return send(res, 200, { data: safeUser(target) }); }
  if (req.method === 'POST' && url.pathname === '/api/auth/reset') { const input = await body(req); const user = (store.users || []).find(item => item.email === String(input.email || '').toLowerCase()); if (!user) return send(res, 200, { message: 'If that account exists, reset instructions have been sent.' }); if (!input.password || String(input.password).length < 8) return send(res, 400, { error: 'New password must be at least 8 characters' }); user.passwordHash = hashPassword(input.password); writeStore(store); return send(res, 200, { message: 'Password reset successfully' }); }
  if (req.method === 'GET' && url.pathname === '/api/admin/listings') { if (!isAdmin(req)) return send(res, 401, { error: 'Admin authentication required' }); return send(res, 200, { data: store.listings, count: store.listings.length }); }
  if (req.method === 'POST' && parts[1] === 'admin' && parts[2] === 'listings' && parts[3] && parts[4] === 'confirm') { if (!isAdmin(req)) return send(res, 401, { error: 'Admin authentication required' }); const listing = store.listings.find(item => String(item.id) === parts[3]); if (!listing) return send(res, 404, { error: 'Listing not found' }); listing.status = 'confirmed'; listing.verified = true; listing.confirmedAt = new Date().toISOString(); const submission = (store.submissions || []).find(item => String(item.listingId) === String(listing.id)); if (submission) { submission.status = 'confirmed'; submission.verified = true; submission.confirmedAt = listing.confirmedAt; } writeStore(store); return send(res, 200, { data: listing, message: 'Listing confirmed and published' }); }
  if (req.method === 'POST' && parts[1] === 'admin' && parts[2] === 'listings' && parts[3] && parts[4] === 'reject') { if (!isAdmin(req)) return send(res, 401, { error: 'Admin authentication required' }); const input = await body(req); const listing = store.listings.find(item => String(item.id) === parts[3]); if (!listing) return send(res, 404, { error: 'Listing not found' }); listing.status = 'rejected'; listing.verified = false; listing.rejectionReason = String(input.reason || 'Listing did not meet verification requirements'); const submission = (store.submissions || []).find(item => String(item.listingId) === String(listing.id)); if (submission) { submission.status = 'rejected'; submission.rejectionReason = listing.rejectionReason; } writeStore(store); return send(res, 200, { data: listing, message: 'Listing rejected' }); }
  if (req.method === 'POST' && parts[1] === 'admin' && parts[2] === 'listings' && parts[3] && parts[4] === 'needs-info') { if (!isAdmin(req)) return send(res, 401, { error: 'Admin authentication required' }); const input = await body(req); const listing = store.listings.find(item => String(item.id) === parts[3]); if (!listing) return send(res, 404, { error: 'Listing not found' }); listing.status = 'needs_info'; listing.verified = false; listing.reviewNote = String(input.reason || 'Please provide more information about this property'); const submission = (store.submissions || []).find(item => String(item.listingId) === String(listing.id)); if (submission) { submission.status = 'needs_info'; submission.reviewNote = listing.reviewNote; } writeStore(store); return send(res, 200, { data: listing, message: 'More information requested' }); }
  if (req.method === 'GET' && url.pathname === '/api/listings') { let items = store.listings.filter(publicListing); const q = (url.searchParams.get('q') || '').toLowerCase(); const city = url.searchParams.get('city'); const neighbourhood = url.searchParams.get('neighbourhood'); const type = url.searchParams.get('type'); const minPrice = Number(url.searchParams.get('minPrice')); const maxPrice = Number(url.searchParams.get('maxPrice')); const beds = Number(url.searchParams.get('beds')); const baths = Number(url.searchParams.get('baths')); if (city) items = items.filter(x => x.city === city); if (neighbourhood) items = items.filter(x => x.neighbourhood === neighbourhood); if (type) items = items.filter(x => x.type === type); if (Number.isFinite(minPrice) && minPrice > 0) items = items.filter(x => x.price >= minPrice); if (Number.isFinite(maxPrice) && maxPrice > 0) items = items.filter(x => x.price <= maxPrice); if (Number.isFinite(beds) && beds > 0) items = items.filter(x => Number(x.beds) >= beds); if (Number.isFinite(baths) && baths > 0) items = items.filter(x => Number(x.baths) >= baths); if (q) items = items.filter(x => `${x.title} ${x.city} ${x.neighbourhood}`.toLowerCase().includes(q)); const sort = url.searchParams.get('sort'); if (sort === 'price-asc') items.sort((a, b) => a.price - b.price); if (sort === 'price-desc') items.sort((a, b) => b.price - a.price); if (sort === 'newest') items.sort((a, b) => new Date(b.createdAt || 0) - new Date(a.createdAt || 0)); return send(res, 200, { data: items, count: items.length }); }
  if (req.method === 'GET' && parts[1] === 'listings' && parts[2]) { const item = store.listings.find(x => x.id === parts[2]); return item ? send(res, 200, { data: item }) : send(res, 404, { error: 'Listing not found' }); }
  if (req.method === 'POST' && url.pathname === '/api/listings') { const input = await body(req); const user = authUser(req); if (!user) return send(res, 401, { error: 'Please log in before posting a property' }); const required = ['title', 'city', 'type', 'price', 'phone']; const missing = required.filter(key => !input[key]); if (missing.length) return send(res, 400, { error: `Missing fields: ${missing.join(', ')}` }); const photos = saveImages(input.photos); const listing = { id: id(), ownerId: user.id, ownerName: user.name, title: input.title, city: input.city, neighbourhood: input.neighbourhood || 'To be confirmed', type: input.type, price: Number(input.price), period: input.period || (input.type === 'Guesthouse' ? 'night' : 'month'), beds: Number(input.beds || 0), baths: Number(input.baths || 0), size: Number(input.size || 0), hue: Number(input.hue || 30), featured: false, verified: false, status: 'pending', description: input.description || 'New property submitted for Findam verification.', photos, phone: input.phone, createdAt: new Date().toISOString() }; const submission = { id: id(), listingId: listing.id, ownerId: user.id, ...input, photos, price: listing.price, status: 'pending', verified: false, createdAt: listing.createdAt }; store.listings.push(listing); store.submissions.push(submission); writeStore(store); return send(res, 201, { data: listing, submission, message: 'Listing created and submitted for verification' }); }
  if (req.method === 'GET' && url.pathname === '/api/me/listings') { const user = authUser(req); if (!user) return send(res, 401, { error: 'Authentication required' }); return send(res, 200, { data: store.listings.filter(item => item.ownerId === user.id) }); }
  if (req.method === 'GET' && url.pathname === '/api/submissions') { if (!isAdmin(req)) return send(res, 401, { error: 'Admin authentication required' }); return send(res, 200, { data: store.submissions || [] }); }
  if ((req.method === 'PUT' || req.method === 'DELETE') && parts[1] === 'listings' && parts[2]) { if (!isAdmin(req)) return send(res, 401, { error: 'Admin authentication required' }); const index = store.listings.findIndex(item => String(item.id) === parts[2]); if (index < 0) return send(res, 404, { error: 'Listing not found' }); if (req.method === 'DELETE') { store.listings.splice(index, 1); store.submissions = (store.submissions || []).filter(item => String(item.listingId) !== parts[2]); store.favorites = (store.favorites || []).filter(item => String(item.listingId) !== parts[2]); writeStore(store); return send(res, 200, { deleted: true }); } const changes = await body(req); const allowed = ['title', 'city', 'neighbourhood', 'type', 'price', 'period', 'beds', 'baths', 'size', 'description', 'photos']; Object.assign(store.listings[index], Object.fromEntries(allowed.filter(key => changes[key] !== undefined).map(key => [key, changes[key]]))); writeStore(store); return send(res, 200, { data: store.listings[index] }); }
  if ((req.method === 'POST' || req.method === 'DELETE') && parts[1] === 'favorites' && parts[2]) { const visitorId = req.method === 'POST' ? (await body(req)).visitorId : url.searchParams.get('visitorId'); if (!visitorId) return send(res, 400, { error: 'visitorId is required' }); store.favorites = store.favorites.filter(x => !(x.visitorId === visitorId && x.listingId === parts[2])); if (req.method === 'POST') store.favorites.push({ visitorId, listingId: parts[2], createdAt: new Date().toISOString() }); writeStore(store); return send(res, 200, { saved: req.method === 'POST' }); }
  if (req.method === 'GET' && url.pathname === '/api/favorites') { const visitorId = url.searchParams.get('visitorId'); return send(res, 200, { data: store.favorites.filter(x => x.visitorId === visitorId).map(x => store.listings.find(l => l.id === x.listingId)).filter(Boolean) }); }
  if (req.method === 'POST' && url.pathname === '/api/bot') { const input = await body(req); return send(res, 200, { reply: botReply(input.message) }); }
  return send(res, 404, { error: 'Route not found' });
}

const server = http.createServer((req, res) => handler(req, res).catch(error => send(res, error.message === 'Invalid JSON' ? 400 : 500, { error: error.message })));
server.listen(port, () => console.log(`Findam API listening on http://localhost:${port}`));
